BLOCK_SITE:
- https://bornforthis.cn/
- https://koxiuqiu.cn/2024/9y12d1/
- ^https?:\/\/(www\.)?bornforthis\.cn\/.*
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: true
LINK:
- link: https://huanxueblog.top/link/
  theme: anzhiyu
MAX_POSTS_NUM: 25
OUTDATE_CLEAN: 10000
SETTINGS_FRIENDS_LINKS:
  enable: false
  json_api: ''
  list:
  - - "AI\u60A6\u521B"
    - https://bornforthis.cn
    - https://bornforthis.cn/aiyc.png
